"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const dotenv_1 = __importDefault(require("dotenv"));
const cors_1 = __importDefault(require("cors"));
const path_1 = __importDefault(require("path"));
dotenv_1.default.config();
const app = (0, express_1.default)();
const PORT = process.env.PORT || 3000;
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use('/uploads', express_1.default.static(path_1.default.join(__dirname, 'uploads')));
app.use('/api/san-pham', require('./routes/sanPhamRoutes').default);
app.use('/api', require('./routes/danhGiaSPRoutes').default);
app.use('/api', require('./routes/nguoiDungRoutes').default);
app.use('/api/gio-hang', require('./routes/gioHangRoutes').default);
app.use('/api/don-hang', require('./routes/donHangRoutes').default);
app.use('/api/danh-muc', require('./routes/danhMucRoutes').default);
app.use('/api/thuong-hieu', require('./routes/thuongHieuRoutes').default);
app.use('/api/mau-sac', require('./routes/mauSacRoutes').default);
app.use('/api/kich-co', require('./routes/kichCoRoutes').default);
app.use('/api/bien-the', require('./routes/bienTheRoutes').default);
app.use('/api/thanh-toan', require('./routes/thanhToanSPRoutes').default);
app.use('/api/giao-dich', require('./routes/giaoDichThanhToanRoutes').default);
app.use('/api/dia-chi', require('./routes/diaChiGiaoHangRoutes').default);
app.use('/api/hinh-anh-sp', require('./routes/hinhAnhSPRoutes').default);
app.listen(PORT, () => {
    console.log(`Server is running on http://localhost:${PORT}`);
});
exports.default = app;
